name: Build Custom Focus App
on:
  workflow_dispatch:
    inputs:
      ipa_url:
        description: 'Direct download link to decrypted YouTube IPA'
        required: true

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Custom Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: brew install make ldid dpkg

      - name: Setup Theos
        uses: actions/checkout@v4
        with:
          repository: theos/theos
          ref: master
          path: theos
          submodules: recursive

      - name: Download iOS SDK
        run: |
          git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/theos/sdks/
          cd sdks
          git sparse-checkout set --no-cone iPhoneOS16.5.sdk
          git checkout
          mv *.sdk ${{ github.workspace }}/theos/sdks

      - name: Clone Required Headers
        run: |
          export THEOS=${{ github.workspace }}/theos
          cd $THEOS/include
          git clone --quiet --depth=1 https://github.com/PoomSmart/YouTubeHeader.git
          git clone --quiet --depth=1 https://github.com/PoomSmart/PSHeader.git

      - name: Compile Custom Tweak
        run: |
          echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH
          export THEOS=${{ github.workspace }}/theos
          make clean
          make package SIDELOADED=1

      - name: Extract Compiled Files
        run: |
          mkdir -p extract
          dpkg-deb -x packages/*.deb extract/
          cp -r extract/Library/MobileSubstrate/DynamicLibraries/YTLite.dylib .
          cp -r "extract/Library/Application Support/YTLite.bundle" .

      - name: Download Clean YouTube IPA
        run: wget "${{ github.event.inputs.ipa_url }}" --no-verbose -O YouTube.ipa

      - name: Inject using Cyan
        run: |
          pipx install --force https://github.com/asdfzxcvbn/pyzule-rw/archive/main.zip
          ~/.local/bin/cyan -i YouTube.ipa -f YTLite.dylib YTLite.bundle -o YouTube_Focus.ipa

      - name: Upload Final IPA
        uses: actions/upload-artifact@v4
        with:
          name: YouTube-Focus-App
          path: YouTube_Focus.ipa
